version: "3"

services:

  rembg-app:
    # build: .
    image: alyetama/rembg-app:latest
    ports:
      - "8501:8501"
    environment:
      - ENABLE_CORS=false
    command: >
      streamlit run streamlit_app.py --server.enableCORS=false --server.enableXsrfProtection=false
    restart: always
    volumes:
      - "./.streamlit:/home/app/.streamlit"
